Fixed issue #27 for empty BLAST output
Having moved from a custom parser to Pandas' from_csv() method
for creating dataframes, I'd failed to account for empty BLASTN
output, so the following error was being raised:

 pandas.io.common.EmptyDataError: No columns to parse from file

After catching this and creating an empty dataframe, the resulting
calculation of ANI percentage identity was returning NaN for those
dataframes, and the revised code notices this, and replaces with
zero, where appropriate.